### ISSUE TITLE
Add ticket number counters to dashboard tab

### ISSUE THREAD

**Issue by wombat1987** [alexbrownies/extra-fresh#3]
Add ticket number counters to the [team dashboard](https://cloudblue.freshdesk.com/a/dashboard/44000001634) tab. The counters are:
BizCrits - Triage - QJ

It should be similar to what we had on the triage link: 
![image](https://user-images.githubusercontent.com/59900177/72395166-917ee280-3773-11ea-9d98-249caf4d6c71.png)

**Comment by kreigan** [comment]
Duplicate for #2
